version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-richdomain-container
    environment:
      - SA_PASSWORD=RichDomain@2023
      - ACCEPT_EULA=Y

  richdomain.api:
    image: ${DOCKER_REGISTRY-}richdomainapi
    container_name: richdomain-api-container
    build:
      context: .
      dockerfile: RichDomain.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS= https://+:443 ;http://+:80
    ports:
     - "80"
     - "443" 
    depends_on:
     - sqldata
